# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32ca7310168d25f678abd13f9408ffffd5b4f379315c870bcdaac3a3e113bbb00a4725cc1aec60275e63efe82194a8f001a74661a6efa923f8c8552a1dabf95f

test:
  secret_key_base: 6214b13861bb70d86c367115146b8cf612e9267723929c8510f86b02c7496371659a9bb4e4eb66f0d5b120868ac6336da621fb72f509ded0ac8fee884abcc76a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
